### ISSUE TITLE
Opencv_Loader BGR

### ISSUE THREAD

**Issue by zhanglaplace** [minivision-ai/Silent-Face-Anti-Spoofing#10]
opencv cv2.imread is Default BGR，but generate_FT is cv2.COLOR_RGB2GRAY，it's correct?

**Comment by zhuyingSeu** [comment]
It has little effect,but it should be cv2.COLOR_BRG2GRAY.

**Comment by zhanglaplace** [comment]
@zhuyingSeu ok
