### ISSUE TITLE
how should the dataset be?

### ISSUE THREAD

**Issue by grdlonur** [minivision-ai/Silent-Face-Anti-Spoofing#11]
Is the dataset you are using an open source dataset or was prepared by you?
I read the data preprocessing section but it was not clear for me.
What should be the dataset structure for training?

**Comment by zhanglaplace** [comment]
同疑问，请教下训练数据是开源数据集还是真实采集的数据，如果是真实采集的数据，攻击部分的数据是否较难采集？

**Comment by zhuyingSeu** [comment]
数据是我们自己采集的数据，攻击部分数据是根据实际应用逐渐积累的。
训练集的目录结构在readme都列出来了。
