### ISSUE TITLE
傅里叶分支问题

### ISSUE THREAD

**Issue by zhanglaplace** [minivision-ai/Silent-Face-Anti-Spoofing#12]
你好，傅里叶分支的target为输入图像经过傅立叶变换后和resize后的结果，而看代码，他的pred是神经网络某一层的特征图，这两者似乎不能做对应。直接求MSELoss貌似也不合原理。你那边能做一下解释吗。

**Comment by zhuyingSeu** [comment]
傅里叶频谱图作为辅助监督，可以理解为ground truth，与原图相关，数据增广的影响不大，你也可以做实验对比一下。

**Comment by FDeagle** [comment]
> 你好，傅里叶分支的target为输入图像经过傅立叶变换后和resize后的结果，而看代码，他的pred是神经网络某一层的特征图，这两者似乎不能做对应。直接求MSELoss貌似也不合原理。你那边能做一下解释吗。

应该是强制让mobilefacenet能够保留频谱特征，用于最终的分类使用

**Comment by zhanglaplace** [comment]
> > 你好，傅里叶分支的target为输入图像经过傅立叶变换后和resize后的结果，而看代码，他的pred是神经网络某一层的特征图，这两者似乎不能做对应。直接求MSELoss貌似也不合原理。你那边能做一下解释吗。
> 
> 应该是强制让mobilefacenet能够保留频谱特征，用于最终的分类使用

@FDeagle 嗯，只能这么理解了，强制要求featuremap中的某一层特征拥有傅立叶频谱特征的区分度。

**Comment by stevenluzheng123456** [comment]
我感覺傅立葉變化做liveness性能有點差啊。。。不知大家試得怎樣

**Comment by zhanglaplace** [comment]
> 我感覺傅立葉變化做liveness性能有點差啊。。。不知大家試得怎樣

性能指得是？看作者的视频说的是准确率提升比较大。

**Comment by stevenluzheng123456** [comment]
我在Video Magificantion 裏使用過傅立葉變化檢測人臉的微動作，準確度不好，作者的方法有paper麼？用傅里叶频谱图另外來做一個監督信號，這個辦法還挺新穎的

**Comment by zhanglaplace** [comment]
> 我在Video Magificantion 裏使用過傅立葉變化檢測人臉的微動作，準確度不好，作者的方法有paper麼？用傅里叶频谱图另外來做一個監督信號，這個辦法還挺新穎的

嗯，我这边在自己的数据集上进行迭代，但是我的攻击样本太少了，所以也不太评估下是否有效。活体还是太吃攻击样本的种类和多样性了

**Comment by Arctanxy** [comment]
同问作者这个傅里叶辅助识别的手段有paper吗？还没发的话能详细讲讲思路吗？

**Comment by lawo123** [comment]
如果直接用傅里叶变换后的图作为输入分类的效果怎么样？有尝试过吗？ @zhuyingSeu
