### ISSUE TITLE
ONNX model !!

### ISSUE THREAD

**Issue by PhenomenalOnee** [minivision-ai/Silent-Face-Anti-Spoofing#13]
Hello, I tried to convert your given model to onnx and converted them successfully, but the output of V1SE model is not consistent with the given pytorch model. I used onnxruntime for inference of the two models.
 V2 model is fine but V1SE is not. Can you help?

**Comment by zhuyingSeu** [comment]
We have updated the caffe models.

**Comment by PhenomenalOnee** [comment]
Well i solved this by modifiying the forward call in SE module.
In file MiniFASNet.py , line 113, i added line
x = torch.mul(module_input,x)
return x
Now both onnx models produces same results as pytorch

**Comment by nhathoang0110** [comment]
@PhenomenalOnee  Can you give me onnx model or source code to convert?

**Comment by PhenomenalOnee** [comment]
@nhathoang0110 sorry brother currently i cant find the script nor the model that i have converted, but i you can use pytorch to onnx conversion. (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)

**Comment by quangvu1798** [comment]
can you lend me your onnx V2 model, i tried converting but the result is different from the original model, i can't fix it

**Comment by TrNgTinh** [comment]
@nhathoang0110 @quangvu1798 Have you successfully converted? i stuff when convert, missing key :((

**Comment by TrNgTinh** [comment]
oh. I just converted and tested successfully :zany_face:

**Comment by Fanfar1c** [comment]
> ой. Я только что преобразовал и успешно протестировал🤪

Можете поделиться кодом

**Comment by Jeremiah0425** [comment]
> oh. I just converted and tested successfully 🤪

Hello,can you share this convert code,thanks.

**Comment by fn-hide** [comment]
> Well i solved this by modifiying the forward call in SE module. In file MiniFASNet.py , line 113, i added line x = torch.mul(module_input,x) return x Now both onnx models produces same results as pytorch

I successfully converted the model to onnx. The results from onnx and pytorch are the same without modification at line 113 in `MiniFASNet.py`. Did I make mistake?

**Comment by fangfap** [comment]
#my code :)))
from torch.autograd import Variable
import torch.onnx
from collections import OrderedDict

from src.model_lib.MiniFASNet import *

# torch_model = MiniFASNetV1SE(conv6_kernel=(5, 5))
torch_model = MiniFASNetV2(conv6_kernel=(5, 5))


state_dict = torch.load(r"resources\anti_spoof_models\2.7_80x80_MiniFASNetV2.pth",map_location=torch.device('cpu'))
# state_dict = torch.load(r"resources\anti_spoof_models\4_0_0_80x80_MiniFASNetV1SE.pth",map_location=torch.device('cpu'))
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:]  # remove `module.`
    new_state_dict[name] = v
torch_model.load_state_dict(new_state_dict)
torch_model.eval()

torch_input = Variable(torch.randn(1, 3, 80, 80))
full_model_path = "resources/anti_spoof_models/v2.onnx"
# model export into ONNX format
torch.onnx.export(
    torch_model,
    torch_input,
    full_model_path,
    verbose=True,
    input_names=["input"],
    output_names=["output"],
    opset_version=10
)

**Comment by phoxx67895-stack** [comment]
i need MiniFASNet.py

**Comment by Jeremiah0425** [comment]
> i need MiniFASNet.py

The source code includes this file.
