### ISSUE TITLE
If without FT

### ISSUE THREAD

**Issue by lazerliu** [minivision-ai/Silent-Face-Anti-Spoofing#14]
Thanks for your excellenct work and share!
I am wondering whether have you done an ablation experiment ,that's how about the model's performance if we remove the FT generator? Because I canot be sure the amazing performance comes from your original CNN model or from the the gain brought by FT.
Looking forward for your reply,thks!

**Comment by zhuyingSeu** [comment]
We have done the ablation experiment.With FT, the performance is better. You can have a try.
