### ISSUE TITLE
手机屏幕图片效果误判率高

### ISSUE THREAD

**Issue by zhengqicl** [minivision-ai/Silent-Face-Anti-Spoofing#15]
你好，我这边调用windows笔记本调用摄像头，然后用手机屏幕打开自拍照，测试效果不是很理想，阈值很高，达到0.99

**Comment by zhengqicl** [comment]
@zhuyingSeu ，摄像头的分辨率设置的是640x480，几年前的笔记本，摄像头像素应该130万

**Comment by smartwell** [comment]
恩，罗技 c525 ，640*480  也是这个问题，阈值很高

**Comment by xuguozhi** [comment]
笔记本的摄像头拍手机屏幕 肯定要拦截的啊
