### ISSUE TITLE
Model 1_80x80 ?

### ISSUE THREAD

**Issue by PhenomenalOnee** [minivision-ai/Silent-Face-Anti-Spoofing#19]
In your Data Processing README Part, you mentioned about three scaling factors 1_80x80, 2.7_80x80 and 4_80x80 and you have provided 2.7 and 4.0 pretrained models but no 1.0 model? Can you provide 1_80x80 model also.
Thank You

**Comment by zhuyingSeu** [comment]
We provived the two models because they were used in APK.They are not pretrained models.

**Comment by PhenomenalOnee** [comment]
So is there any 1_80x80 model that you have trained and can share?
