### ISSUE TITLE
视频里讲到只用了crop数据增强，不能用像素值扰动，为啥这里还有亮度之类的数据扰动？

### ISSUE THREAD

**Issue by Darknesszlx** [minivision-ai/Silent-Face-Anti-Spoofing#20]
https://github.com/minivision-ai/Silent-Face-Anti-Spoofing/blob/b6d5f04ad78778917853b25c778acef6d5626d15/src/data_io/dataset_loader.py#L18-L19

**Comment by zhuyingSeu** [comment]
视频里讲的是测试图片，训练图片可以适当做一些预处理。
