### ISSUE TITLE
Model Architecture for Scale1_80x80 Training

### ISSUE THREAD

**Issue by PhenomenalOnee** [minivision-ai/Silent-Face-Anti-Spoofing#21]
Hello,

Is it possible to provide just the model architecture file for Scale 1 80x80 
Then i can train on my own database and share with you.

Does Scale 1 model needs Squeeze Excitation module for training?

Thanks,

**Comment by zhuyingSeu** [comment]
We trained the models with SE and without SE.The pretrained model is not important.Have you trained Sacle2.7 and Scale4.0 model?

**Comment by zhuyingSeu** [comment]
We trained the models with SE and without SE.For diffenent datasets and scales, the effect of SE 
is uncertain. Have you trained the sacle2.7 and scale4.0 model?

**Comment by PhenomenalOnee** [comment]
Not yet i was thinking of training with scale 1.0 thats why i want to know whether you can provide your scale 1.0 model architecture or you have used one of the existing architectures in MiniFASNet.py file

**Comment by zhuyingSeu** [comment]
The scale is only related with the images. The model architectures are in the MiniFASNet.py.
