### ISSUE TITLE
anti_spoof_predict代码有可以优化的地方

### ISSUE THREAD

**Issue by GengCauWong** [minivision-ai/Silent-Face-Anti-Spoofing#23]
把_load_model放到__init__里面，否则用摄像头实时测试的时候，每次都要重新加载一遍模型浪费时间

**Comment by ligaoyuan-potato** [comment]
不可以，因为代码里面是轮流加载模型测试的

**Comment by zhuyingSeu** [comment]
为了说明测试流程，提供了一个简单的图像测试脚本。至于具体的使用，可以自己根据需求改。如果写在__init__里，需要分别加载模型，注意不同scale对应的模型。

**Comment by ligaoyuan-potato** [comment]
谢谢，我已经测试好了，想在训练一下活体检测这个模型，请问下三个类别是怎么划分的？需要多大的数据量呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minivision-ai/Silent-Face-Anti-Spoofing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午5:17
收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] anti_spoof_predict代码有可以优化的地方 (#23)





 
为了说明测试流程，提供了一个简单的图像测试脚本。至于具体的使用，可以自己根据需求改。如果写在__init__里，需要分别加载模型，注意不同scale对应的模型。

**Comment by ligaoyuan-potato** [comment]
谢谢，我已经测试好了，想在训练一下活体检测这个模型，请问下三个类别是怎么划分的？需要多大的数据量呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minivision-ai/Silent-Face-Anti-Spoofing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午5:17
收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] anti_spoof_predict代码有可以优化的地方 (#23)





 
为了说明测试流程，提供了一个简单的图像测试脚本。至于具体的使用，可以自己根据需求改。如果写在__init__里，需要分别加载模型，注意不同scale对应的模型。

**Comment by zhuyingSeu** [comment]
三类分别为2D假脸（0类），真脸（1类），假脸（2类），你有多少数据就用多少，我们的量级是每类差不多五百万。
