### ISSUE TITLE
Dataset Overview?

### ISSUE THREAD

**Issue by PhenomenalOnee** [minivision-ai/Silent-Face-Anti-Spoofing#25]
Hello, i really want to understand what type of dataset you used. I know it has three class: 2D-Fake, 3D-Fake and Real but my question is can you provide a sample images of these three classes.
Also have you used any opensource dataset like CelebA or FFHQ for Real face samples. And How you collected these dataset. Just an overview will help in training.
Also can you describe the procedure how you collected/make the dataset, and size of the dataset (number of images for each class)

Thanks

**Comment by zhuyingSeu** [comment]
We put the images of the same class in the same folder. Due to the privacy, we can not provide the samples. CelebA contains the three classes. We made the dataset according to the practical application scenarios.There are about 5 million images in each class.

**Comment by PhenomenalOnee** [comment]
I didn't get this: CelebA contains the three classes
So did you use any opensource datasets or build all data (total of 5*3 million images) by yourself.
Also can you tell have you used same persons faces across all three classes or random people images in three classes?
Thank You

**Comment by zhuyingSeu** [comment]
You can see the sample of each class in the CelebA because it contains  2D-Fake, 3D-Fake and Real images. We did not use any open source datasets.Random people images in thress classes.
