### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by yanjun3235** [minivision-ai/Silent-Face-Anti-Spoofing#27]
MultiFTNet.py修改： self.model = MiniFASNetV2SE(...) 改为self.model = MiniFASNetV1SE(...) , 图像处理为1_80x80, 训练出来的模型大小是2690，原生resources下的4_0_0_80x80_MiniFASNetV1SE.pth 大小为1813，请问这是怎么回事 ？？

**Comment by zhuyingSeu** [comment]
因傅里叶辅助监督分支只用于模型的训练阶段, 测试不需要该分支,所以在实际使用时,对模型进行了删除傅里叶分支的处理以降低模型的大小.

**Comment by notha99y** [comment]
@zhuyingSeu possible to share the model pruning code?

**Comment by zhuyingSeu** [comment]
At present, we don't share the prunning code.

**Comment by zj19921221** [comment]
> 因傅里叶辅助监督分支只用于模型的训练阶段, 测试不需要该分支,所以在实际使用时,对模型进行了删除傅里叶分支的处理以降低模型的大小.

 hi @zhuyingSeu   你好 能否留一个邮箱，有问题想请教下你；在你的主页没有看到邮箱地址；
感谢；

**Comment by zhuyingSeu** [comment]
zhuying@minivision.cn
