### ISSUE TITLE
根本一点都不准确，太差了，对准图片，手不要抖动拍照就会骗过算法；训练部分用到光流，识别部分也用上吧！！

### ISSUE THREAD

**Issue by WIKI2020** [minivision-ai/Silent-Face-Anti-Spoofing#28]
更本一点都不准确，太差了，对准图片，手不要抖动拍照就会骗过算法；训练部分用到光流，识别部分也用上吧！

**Comment by zj19921221** [comment]
> 更本一点都不准确，太差了，对准图片，手不要抖动拍照就会骗过算法；训练部分用到光流，识别部分也用上吧！

哈哈哈 这个本来就是他的小模型版本；应该是还有一个大模型版本付费的

**Comment by zhuyingSeu** [comment]
1.不同场景，阈值稍有差异，您可以关注真脸与假脸的置信度，试试调节阈值。2.不同手机型号，前置摄像头的成像有差异，体验也有一定差异的。

**Comment by liuqunzhong** [comment]
训练部分用的傅里叶 没有用到光流吧？
