### ISSUE TITLE
Can't detect photo attack

### ISSUE THREAD

**Issue by wangxianliang** [minivision-ai/Silent-Face-Anti-Spoofing#3]
Almost all face photos are classified as live face.

**Comment by zhuyingSeu** [comment]
Can you send the photos to the mailbox: zhuying@minivision.cn ?

**Comment by zhuyingSeu** [comment]
Use the test.py or APK?

**Comment by wangxianliang** [comment]
mobile apk.

**Comment by zhuyingSeu** [comment]
In different scenarios, the threshold is slightly different. You can try to adjust the threshold.(Click the icon in the upper right corner to adjust the threshold.)

**Comment by RizhaoCai** [comment]
Have you tried to find a threshold that can discriminate photo attacks from genuine faces?
