### ISSUE TITLE
convert caffe model not work well

### ISSUE THREAD

**Issue by yanjun3235** [minivision-ai/Silent-Face-Anti-Spoofing#31]
使用PytorchToCaffe转换出来的模型(转换的prototxt与官方的一样)，输入图片推理得到的3个值一样大小，用官方提供的推理没有问题, 请问是哪里出了问题 ？是否可以提供转换caffe模型的工具

**Comment by zhuyingSeu** [comment]
转换的模型有没有SE结构?如果有SE结构,PytorchToCaffe转换会有问题的,我们的caffe转换工具暂不开源.
