### ISSUE TITLE
Do you have a validation dataset for training?

### ISSUE THREAD

**Issue by luan1412167** [minivision-ai/Silent-Face-Anti-Spoofing#33]
Hi you, thanks for your work. I have read your code and seem as you don't use validation in training process.
Whether Am I wrong? Can you clarify it for me. I am very appreciated it. Thank you!!

**Comment by zhuyingSeu** [comment]
We just provide the simple training project. You can add validation staege according to your need.

**Comment by zhuyingSeu** [comment]
We just provide the simple training project. You can add the validation stage according to your need.

**Comment by luan1412167** [comment]
> We just provide the simple training project. You can add the validation stage according to your need.

thanks for your reply. Can you share with me how to downsize the model efficiently? Right now, I'm training my dataset about 20k samples. Model seems as overfitting with 99.99% in training data although my data have a few noises.
