### ISSUE TITLE
變為即時影像偵測

### ISSUE THREAD

**Issue by HsiaoCH** [minivision-ai/Silent-Face-Anti-Spoofing#34]
我現在在嘗試使用電腦相機去做即時的偵測與顯示，我是以cpu去跑，但其FPS不盡理想，不能像demo上的動圖一樣理想，我是以更改test.py去完成，請問更改test.py需要注意些甚麼?請問影響FPS最大部分code是?

**Comment by zhuyingSeu** [comment]
cpu会比gpu慢很多,还有就是电脑的性能,视频实时测试可能得修改加载模型的那部分逻辑,改为初始化加载模型,这样就不用每帧都加载模型.

**Comment by HsiaoCH** [comment]
我明白了，感謝您的回覆
