### ISSUE TITLE
PReLU转化问题

### ISSUE THREAD

**Issue by Silencesss** [minivision-ai/Silent-Face-Anti-Spoofing#35]
您好，这项工作非常好，但是在实际使用中我想将开源的caffemodel转化为TensorRT，但是TensorRT不支持PReLU层，我想请问一下，这个PReLU层该怎么转化为TensorRT支持的Relu层呢？非常感谢。

**Comment by zhuyingSeu** [comment]
TensorRT的相关问题,你可以关注TensorRT的相关社区论坛,如果没有解决方案,那可能需要将模型的PRelu改成Relu重新训练模型(模型精度可能会稍有下降).
