### ISSUE TITLE
训练集分为3类是哪三类？

### ISSUE THREAD

**Issue by rocinant** [minivision-ai/Silent-Face-Anti-Spoofing#36]
作者你好，将训练集分为3类是哪三类啊？我理解不是应该只有两类吗？真脸和假脸？

**Comment by JiliuLiSU** [comment]
同问

**Comment by shopping-tang** [comment]
https://zhuanlan.zhihu.com/p/163022088  楼上两位兄弟，这个链接里说了，数据划分为三类，分别为真脸、2D假脸（纸质攻击、视频攻击）及3D假脸（3D人脸、3D模具等）。

**Comment by rocinant** [comment]
看到了，感谢
