### ISSUE TITLE
門檻值問題

### ISSUE THREAD

**Issue by HsiaoCH** [minivision-ai/Silent-Face-Anti-Spoofing#38]
詢問門檻值的調整是否於下列參數？
anti_spoof_predict.py
`self.detector_confidence = 0.6`

我在這個值所作的調整，並沒有反應到我的預測結果中
0.8,0.7,0.5,1.0接會出現相同的預測結果

想請問決定門檻值的正確參數是？

**Comment by rocinant** [comment]
I think that one is clearly for the detected face's bbox confidence not for anti spoofing. You can directly read model's final output and compare it to recommend value which is 0.913 I think.

**Comment by HsiaoCH** [comment]
Thanks for reply
