### ISSUE TITLE
org_1_heightxwidth是80x60吗？

### ISSUE THREAD

**Issue by yisampi** [minivision-ai/Silent-Face-Anti-Spoofing#4]
原图(org_1_heightxwidth),直接将原图resize到固定尺寸(width, height),如图1所示;
![image](https://user-images.githubusercontent.com/22785527/87639064-4babd280-c734-11ea-9b23-fb55fb0e78a6.png)
原图(org_1_heightxwidth)是把数据集中宽高比为width/height=3/4的图片resize到80*60 后得到的吗？

**Comment by zhuyingSeu** [comment]
将原始数据直接resize到80x60.
