### ISSUE TITLE
關於train的一些問題

### ISSUE THREAD

**Issue by HsiaoCH** [minivision-ai/Silent-Face-Anti-Spoofing#40]
由於我以雜誌上的人去做驗證，發現效果並不佳，所以我想train來提昇這部份
我在train時碰到些問題想詢問一下：
1. 我需要在datasets下依目錄格式去去建立資料夾並放入我要的訓練的資料？
2. patch_info參數應該選org_1_80x60 / 1_80x80 / 2.7_80x80 / 4_80x80，也就是說它只會訓練我選的資料？
3. org_1_80x60，下有0、1、2的資料夾，應該為標籤，請問真臉、假臉2d、假臉3d分別對應標籤0、1、2？
4. 要訓練的資料需要先自行調整這些格式（org_1_80x60 / 1_80x80 / 2.7_80x80 / 4_80x80）？
5. 可以發布每個標籤的訓練資料各一比嗎？希望有個範本來建立自己的資料集

**Comment by zhuyingSeu** [comment]
1.数据默认放在datasets目录下，放在其他地方也可以，需要修改相应的代码；
2.patch_info相关内容参考readme中的数据预处理部分；
3.标签可以自己定，没有具体的规定。

**Comment by HsiaoCH** [comment]
```
UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]

_0.7153459191322327
_tensor([0.3333])
epoch 1 started
lr:  [0.1]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
_0.6424510478973389
_tensor([0.3333])
epoch 2 started
lr:  [0.1]
```
謝謝你的回覆，目前看起來能夠train（雖然只以兩筆資料測試）
但我還有些問題想追加詢問
1.這個train.py是訓練目前模型？還是從頭開始訓練？
2.saved_logs是訓練完的結果位置，請問我該如何利用其結果去驗證？
3.資料前處理需要在放入1_80x80 前就做好處理嗎？

**Comment by zhuyingSeu** [comment]
1.可以finetune也可以从头训练，这个都是可以自己设置的；
2.log是用来观测训练过程中相关指标的变化，具体指标也是根据自己的需要设置的；
3.图像需要提前处理放在对应的scale_heightxwidth目录下。
