### ISSUE TITLE
Using provided pretrained models for finetuning

### ISSUE THREAD

**Issue by notha99y** [minivision-ai/Silent-Face-Anti-Spoofing#41]
Firstly, I would like to thank the minivision group for sharing the source code and trained weights with the open source community. The documentation on the README is great too. You guys even put in the effort to translate them into english. Thank you very much. 

I am currently trying to use the pretrained weights provide to fine tune them to my dataset (only 2 class, real or spoof) but i am facing some problems. Is there any tips to doing so?

I note that the state_dict you provided has been pruned before and looking that the way you loaded the models, i see you did the following:

 ```python
state_dict = torch.load(model_path, map_location=self.device)
        keys = iter(state_dict)
        first_layer_name = keys.__next__()
        if first_layer_name.find('module.') >= 0:
            from collections import OrderedDict
            new_state_dict = OrderedDict()
            for key, value in state_dict.items():
                name_key = key[7:]
                new_state_dict[name_key] = value
            self.model.load_state_dict(new_state_dict)
        else:
            self.model.load_state_dict(state_dict)
```
where you only used sliced state_dict.

**Comment by notha99y** [comment]
In addition, I have two follow up questions:
1. when i trained my own 1.0x and 2.7x models from scratch, my model performance pale in comparison compared to yours. I had additional layers with name prepended with `model.`. I had run the following code to load the models

```python
new_state_dict = OrderedDict()
for key, value in state_dict.items():
    if key.find('module.') >= 0:
        
        name_key = key[7:]
        
    if name_key.find('model.') >= 0:
        name_key = name_key[6:]
    new_state_dict[name_key] = value

model.load_state_dict(new_state_dict, strict=False)
```
this gave me some warning
```python
**_IncompatibleKeys(missing_keys=[], unexpected_keys=['FTGenerator.ft.0.weight', 'FTGenerator.ft.0.bias', 'FTGenerator.ft.1.weight', 'FTGenerator.ft.1.bias', 'FTGenerator.ft.1.running_mean', 'FTGenerator.ft.1.running_var', 'FTGenerator.ft.1.num_batches_tracked', 'FTGenerator.ft.3.weight', 'FTGenerator.ft.3.bias', 'FTGenerator.ft.4.weight', 'FTGenerator.ft.4.bias', 'FTGenerator.ft.4.running_mean', 'FTGenerator.ft.4.running_var', 'FTGenerator.ft.4.num_batches_tracked', 'FTGenerator.ft.6.weight', 'FTGenerator.ft.6.bias', 'FTGenerator.ft.7.weight', 'FTGenerator.ft.7.bias', 'FTGenerator.ft.7.running_mean', 'FTGenerator.ft.7.running_var', 'FTGenerator.ft.7.num_batches_tracked'])**
```
which i ignored. Was wondering if there any thing I did wrongly here

2. I note that you have two versions of keep_dict where you hard coded the values. I see them being added into the model code. Could you share what do they mean and how did you derive these values? 

Thanks in advance

**Comment by zhuyingSeu** [comment]
1.if key contains 'Module', it means that the model was trained on cluster.
2.The warning means the finetuned model is lack of  the parameters of FTGenerator branch, it does not matter.

**Comment by notha99y** [comment]
thanks for the reply. then what about the key model.?

also, from my first 

> Firstly, I would like to thank the minivision group for sharing the source code and trained weights with the open source community. The documentation on the README is great too. You guys even put in the effort to translate them into english. Thank you very much.
> 
> I am currently trying to use the pretrained weights provide to fine tune them to my dataset (only 2 class, real or spoof) but i am facing some problems. Is there any tips to doing so?
> 
> I note that the state_dict you provided has been pruned before and looking that the way you loaded the models, i see you did the following:
> 
> ```python
> state_dict = torch.load(model_path, map_location=self.device)
>        keys = iter(state_dict)
>        first_layer_name = keys.__next__()
>        if first_layer_name.find('module.') >= 0:
>            from collections import OrderedDict
>            new_state_dict = OrderedDict()
>            for key, value in state_dict.items():
>                name_key = key[7:]
>                new_state_dict[name_key] = value
>            self.model.load_state_dict(new_state_dict)
>        else:
>            self.model.load_state_dict(state_dict)
> ```
> 
> where you only used sliced state_dict.

is it possible to fine tune your pretrained models?

**Comment by zhuyingSeu** [comment]
You can finetune the model.But you have to initialize the FT Generator parameters because the pretrained models with FT Generator parameters.

**Comment by yunchangxiaoguan** [comment]
> thanks for the reply. then what about the key model.?
> 
> also, from my first
> 
> > Firstly, I would like to thank the minivision group for sharing the source code and trained weights with the open source community. The documentation on the README is great too. You guys even put in the effort to translate them into english. Thank you very much.
> > I am currently trying to use the pretrained weights provide to fine tune them to my dataset (only 2 class, real or spoof) but i am facing some problems. Is there any tips to doing so?
> > I note that the state_dict you provided has been pruned before and looking that the way you loaded the models, i see you did the following:
> > ```python
> > state_dict = torch.load(model_path, map_location=self.device)
> >        keys = iter(state_dict)
> >        first_layer_name = keys.__next__()
> >        if first_layer_name.find('module.') >= 0:
> >            from collections import OrderedDict
> >            new_state_dict = OrderedDict()
> >            for key, value in state_dict.items():
> >                name_key = key[7:]
> >                new_state_dict[name_key] = value
> >            self.model.load_state_dict(new_state_dict)
> >        else:
> >            self.model.load_state_dict(state_dict)
> > ```
> > 
> > 
> > where you only used sliced state_dict.
> 
> is it possible to fine tune your pretrained models?



> In addition, I have two follow up questions:
> 
> 1. when i trained my own 1.0x and 2.7x models from scratch, my model performance pale in comparison compared to yours. I had additional layers with name prepended with `model.`. I had run the following code to load the models
> 
> ```python
> new_state_dict = OrderedDict()
> for key, value in state_dict.items():
>     if key.find('module.') >= 0:
>         
>         name_key = key[7:]
>         
>     if name_key.find('model.') >= 0:
>         name_key = name_key[6:]
>     new_state_dict[name_key] = value
> 
> model.load_state_dict(new_state_dict, strict=False)
> ```
> 
> this gave me some warning
> 
> ```python
> **_IncompatibleKeys(missing_keys=[], unexpected_keys=['FTGenerator.ft.0.weight', 'FTGenerator.ft.0.bias', 'FTGenerator.ft.1.weight', 'FTGenerator.ft.1.bias', 'FTGenerator.ft.1.running_mean', 'FTGenerator.ft.1.running_var', 'FTGenerator.ft.1.num_batches_tracked', 'FTGenerator.ft.3.weight', 'FTGenerator.ft.3.bias', 'FTGenerator.ft.4.weight', 'FTGenerator.ft.4.bias', 'FTGenerator.ft.4.running_mean', 'FTGenerator.ft.4.running_var', 'FTGenerator.ft.4.num_batches_tracked', 'FTGenerator.ft.6.weight', 'FTGenerator.ft.6.bias', 'FTGenerator.ft.7.weight', 'FTGenerator.ft.7.bias', 'FTGenerator.ft.7.running_mean', 'FTGenerator.ft.7.running_var', 'FTGenerator.ft.7.num_batches_tracked'])**
> ```
> 
> which i ignored. Was wondering if there any thing I did wrongly here
> 
> 1. I note that you have two versions of keep_dict where you hard coded the values. I see them being added into the model code. Could you share what do they mean and how did you derive these values?
> 
> Thanks in advance

hello，do you solve this question? i train the model ,but when i test it return error, i changed as you ,but also has error

python test.py 
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    test(args.image_name, args.model_dir, args.device_id)
  File "test.py", line 59, in test
    prediction += model_test.predict(img, os.path.join(model_dir, model_name))
  File "/ywcx/guanxiao/Silent-Face-Anti-Spoofing/src/anti_spoof_predict.py", line 92, in predict
    self._load_model(model_path)
  File "/ywcx/guanxiao/Silent-Face-Anti-Spoofing/src/anti_spoof_predict.py", line 81, in _load_model
    self.model.load_state_dict(new_state_dict)
  File "/home/guanxiao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MiniFASNetSE:
	Unexpected key(s) in state_dict: "FTGenerator.ft.0.weight", "FTGenerator.ft.0.bias", "FTGenerator.ft.1.weight", "FTGenerator.ft.1.bias", "FTGenerator.ft.1.running_mean", "FTGenerator.ft.1.running_var", "FTGenerator.ft.1.num_batches_tracked", "FTGenerator.ft.3.weight", "FTGenerator.ft.3.bias", "FTGenerator.ft.4.weight", "FTGenerator.ft.4.bias", "FTGenerator.ft.4.running_mean", "FTGenerator.ft.4.running_var", "FTGenerator.ft.4.num_batches_tracked", "FTGenerator.ft.6.weight", "FTGenerator.ft.6.bias", "FTGenerator.ft.7.weight", "FTGenerator.ft.7.bias", "FTGenerator.ft.7.running_mean", "FTGenerator.ft.7.running_var", "FTGenerator.ft.7.num_batches_tracked". 
	size mismatch for prob.weight: copying a param with shape torch.Size([3, 128]) from checkpoint, the shape in current model is torch.Size([4, 128])

what's the problem?thank you

**Comment by notha99y** [comment]
Hi @yunchangxiaoguan it been awhile since i touched this. I would look at it again and let you know. Probably next week

**Comment by yunchangxiaoguan** [comment]
> Hi @yunchangxiaoguan it been awhile since i touched this. I would look at it again and let you know. Probably next week

ok,thank you so much

**Comment by souviksv** [comment]
@notha99y  same problem I'm also facing.

**Comment by notha99y** [comment]
@yunchangxiaoguan could you try this?
```python
model_dir = 'resources/local_trained/' # my local directory
model_paths = sorted(list(Path(model_dir).glob('*.pth')))

state_dict = torch.load(model_paths[0])

new_state_dict = OrderedDict()
for key, value in state_dict.items():
    if key.find('module.') >= 0:
        
        name_key = key[7:]
        
    if name_key.find('model.') >= 0:
        name_key = name_key[6:]
    new_state_dict[name_key] = value

params = {
    'embedding_size': 128,
    'conv6_kernel': (5,5),
    'drop_p': 0.75,
    'num_classes': 2,
    'img_channel': 3
}

model = MiniFASNetV2SE(**params)

model.load_state_dict(new_state_dict, strict=False)
```
