### ISSUE TITLE
训练自己的数据

### ISSUE THREAD

**Issue by hufangjian** [minivision-ai/Silent-Face-Anti-Spoofing#44]
您好，我测试了你们的模型，在我这边的场景下效果并不是很好。我的场景是红外摄像头灰度图，请问一下用你们的工程训练效果会好使吗？或者您那边有一些好的建议吗？

**Comment by zhuyingSeu** [comment]
我们的红外场景也是用的一样的训练方法，输入图片是单通道的。

**Comment by hufangjian** [comment]
好的，非常感谢，再请教一个问题。我训练的数据的假脸是用摄像头采集电脑屏幕生成的，测试的时候准确率还可以，但是测试用摄像头采集的手机假脸时效果不好，这个是模型泛化能力不好，加相关数据效果是否会好一点？

**Comment by zhuyingSeu** [comment]
电脑屏幕与手机屏幕还是有一定差异的，训练集需要加入测试场景的数据。红外活体一般不考虑电子屏幕，因为成像完全看不清人脸。
