### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by jtlz2** [minivision-ai/Silent-Face-Anti-Spoofing#45]
Thank you so much for such amazing code - and for making your weights available!

Do you have ROC curves for assessing performance?

Have you run the classifier over any available benchmark data sets?

Thanks again!

**Comment by zhuyingSeu** [comment]
We train the models with our own data sets. You can train and test with the public data sets.

**Comment by jtlz2** [comment]
Thanks, indeed.

What do the performance curves look like when you train the models using your own data sets?

**Comment by zhuyingSeu** [comment]
The curves are normal. You can see the key performance in the readme.
