### ISSUE TITLE
confidence大于1

### ISSUE THREAD

**Issue by guijuzhejiang** [minivision-ai/Silent-Face-Anti-Spoofing#48]
感谢分享，我用你的模型重新做预测，图片resize到80*80，发现每个模型输出的confidence都有大于1的情况。请问模型输出的范围不是0--1吗？还是我做错了什么呢？

**Comment by gjd2017** [comment]
> 感谢分享，我用你的模型重新做预测，图片resize到80*80，发现每个模型输出的confidence都有大于1的情况。请问模型输出的范围不是0--1吗？还是我做错了什么呢？
模型网络是没有softmax层的，推理端需要加上
