### ISSUE TITLE
What kind of images are going to be in the 0, 1, 2 folders under each image folders ?

### ISSUE THREAD

**Issue by songinmok63** [minivision-ai/Silent-Face-Anti-Spoofing#56]
You say image folders are,

├── datasets
    └── RGB_Images
        ├── org_1_80x60
            ├── 0
		├── aaa.png
		├── bbb.png
		└── ...
            ├── 1
		├── ddd.png
		├── eee.png
		└── ...
            └── 2
		├── ggg.png
		├── hhh.png
		└── ...
        ├── 1_80x80
        └── ...

What kind of images are going to be in the 0, 1, 2 folders under each image folders (org_1_80x80, 1_80x80 etc) ?
For example, 0 are live images, 1 are print images, 2 are mobile images ...

Sincerely yours.

**Comment by alexcruz0202** [comment]
@songinmok63 
Did you find correct answer for that?

**Comment by songinmok63** [comment]
> @songinmok63
> Did you find correct answer for that?

I don't know that I have correct answer, but I have selected the 0 is print, the 1 is real, and the 2 is mobile.

**Comment by alexcruz0202** [comment]
thanks for your help.

**Comment by zhuyingSeu** [comment]
> > @songinmok63
> > Did you find correct answer for that?
> 
> I don't know that I have correct answer, but I have selected the 0 is print, the 1 is real, and the 2 is mobile.

If you don't have the 3D fake faces, the way you select images is propriate.
