### ISSUE TITLE
怎么判断是否有摩尔纹?

### ISSUE THREAD

**Issue by yangjian1218** [minivision-ai/Silent-Face-Anti-Spoofing#59]
模型是利用有摩尔纹跟没有摩尔纹数据集进行训练,这是人为区分出来的.
如果不人为区分,有什么方法可以判断一张图片是否有摩尔纹,是否有什么指标判断摩尔纹程度?

**Comment by zhuyingSeu** [comment]
模型的训练集没有人为区分是否有摩尔纹，部分电子屏幕假脸有摩尔纹。傅里叶频谱图可以用于观测图像是否有摩尔纹。

**Comment by yangjian1218** [comment]
> 模型的训练集没有人为区分是否有摩尔纹，部分电子屏幕假脸有摩尔纹。傅里叶频谱图可以用于观测图像是否有摩尔纹。

您好,请问您能再详细说一下傅里叶频谱判断摩尔纹么?谢谢? 因为我发现该模型在判断电子屏上不是很准确呀.
