### ISSUE TITLE
Combination strategy

### ISSUE THREAD

**Issue by duongbk61** [minivision-ai/Silent-Face-Anti-Spoofing#61]
I see in your code, the last result is mean of two models.
But if input image only can scale < 2,7 such as 2.0. So is this combination give good result ?
You have any special combination strategy for this cases.

Thanks for reading my issue.

**Comment by duongbk61** [comment]
Another question, if i just care about the face is fake or real, It is better to train the model with 2 or 3 subclasses ?

**Comment by zhuyingSeu** [comment]
You  can try different scales, then combine models. The combination strategy is private.The number of classes mainly depends on the your data set because you have to balance the data of each class.
