### ISSUE TITLE
Fake shown as real

### ISSUE THREAD

**Issue by assman** [minivision-ai/Silent-Face-Anti-Spoofing#62]
This is a fake face showing as real face with 0.99 - 1.00 confidence.
![Screen Shot 2021-05-16 at 2 27 27 PM](https://user-images.githubusercontent.com/14093665/118387823-3012a080-b653-11eb-82ff-49e5cbc7e6ca.png)

<img width="548" alt="Screen Shot 2021-05-16 at 2 14 27 PM" src="https://user-images.githubusercontent.com/14093665/118387427-1a9c7700-b651-11eb-8424-3798667a4698.png">

<img width="533" alt="Screen Shot 2021-05-16 at 2 06 19 PM" src="https://user-images.githubusercontent.com/14093665/118387311-6864af80-b650-11eb-8ede-7a4c98ea2c24.png">

**Comment by assman** [comment]
#3

**Comment by UncleLLD** [comment]
so do I

![xxxx](https://z3.ax1x.com/2021/06/08/2ryMjI.png)

**Comment by vtn98** [comment]
I have also face this problem

**Comment by zhuyingSeu** [comment]
The open source model has its limitations.
