### ISSUE TITLE
Can the accuracy be improved by increasing the image size?

### ISSUE THREAD

**Issue by songinmok63** [minivision-ai/Silent-Face-Anti-Spoofing#63]
I trained and tested the images I collected myself and got good results.
Thank you so much.
Currently, the input image size is set to 80 x 80. If this is 160 x 160, will the accuracy be higher?
And, if the input image is enlarged, is it possible to train without modifying the learning model?

**Comment by jetgoog** [comment]
Have you resolved the issue that current models are only good for vertical screen? Do you mind sharing your models? Thanks.

**Comment by duongbk61** [comment]
If you scale input to 160x160, you have to modify MultiFTNet with new size of input

**Comment by songinmok63** [comment]
Thank you for your recommendation.
And what do you mean to modify MultiFTNet with new size of input, there is not 'input size' in it.
