### ISSUE TITLE
4_0_0_80x80_MiniFASNetV1SE.pth这个权重的模型效果不好

### ISSUE THREAD

**Issue by hongyaohongyao** [minivision-ai/Silent-Face-Anti-Spoofing#67]
直接使用MiniFASNetV2在摄像头下能够把人区别的很清楚，但是MiniFASNetV1SE的权重输出的分类概率的浮动却很大。是否是适应的场景有所不同？
个人重新观察模型的原理，是否四倍的缩放考虑了过多的环境信息？

**Comment by zhuyingSeu** [comment]
不同的模型有不同的局限性，所以才会模型组合使用。
