### ISSUE TITLE
Convert model to rk3288 encountered problems

### ISSUE THREAD

**Issue by lishanlu136** [minivision-ai/Silent-Face-Anti-Spoofing#69]
When I converted the model to the RK3288 platform, the prediction ran into problems and all the images were predicted as spoofing faces. My conversion process is pth - >onnx->rknn, and the onnx model prediction has been verified to be correct. Please remind me of the points that need to be paid attention to during the conversion process. I look forward to hearing from you. Thank you.

**Comment by lishanlu136** [comment]
Resolved, look at the author's transform.to_tensor() function and see that 255 is not changed to 1. So, the scale does not need to be set to 255

**Comment by Nabin-Subedi** [comment]
The output from the converted onnx model is vastly different from that of the original model. can you suggest how you did the conversion correctly
