### ISSUE TITLE
Why no pading to square before resizing

### ISSUE THREAD

**Issue by KitWong2048** [minivision-ai/Silent-Face-Anti-Spoofing#7]
你好，请问为什么预处理的时候不先把人脸框padding 成square然后再做resize呢，这样不会另到人脸框的aspect ratio 变化造成畸变吗

**Comment by zhuyingSeu** [comment]
与人脸检测器输出的bbox相关，这里默认人脸检测器输出的bbox是正方形，如果不是正方形，需要调整为正方形。
