### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by DoubangoTelecom** [minivision-ai/Silent-Face-Anti-Spoofing#70]
Hello,

I'd like to commend you for your excellent software.

We did a stress test on your implementation and you can find a [video](https://www.youtube.com/watch?v=vTrKZ5v_MOQ) at [1] and [summary](https://www.doubango.org/SDKs/face-liveness/docs/Testing_the_competition.html#minivision-ai-turingtech-vip) at [2].

From your home page I see that you have a more accurate version but it's private. **How could we test that private version?**

[1] https://www.youtube.com/watch?v=vTrKZ5v_MOQ

[2] https://www.doubango.org/SDKs/face-liveness/docs/Testing_the_competition.html#minivision-ai-turingtech-vip

Thanks

**Comment by zhuyingSeu** [comment]
Thanks for your test.You can contact us via https://ai.minivision.cn/#/mainIndex
