### ISSUE TITLE
输入图片的ToTensor变换问题

### ISSUE THREAD

**Issue by bldu** [minivision-ai/Silent-Face-Anti-Spoofing#72]
观察到作者改写了pytorch自带的ToTensor算子，把除以255给去掉了。这样输入的图片就没有缩放到0-1。请问这样做是有什么特别的原因吗？我尝试用pytorch自带的ToTensor，结果就变得很差。不知道原因是什么

**Comment by zhuyingSeu** [comment]
我们做过对比实验，这个影响不大。
