### ISSUE TITLE
Doesn't work well with back camera

### ISSUE THREAD

**Issue by francorobles** [minivision-ai/Silent-Face-Anti-Spoofing#74]
Tested using the back camera by comparing 2 different pictures and the result is higher than 0.8. No issues on the front camera though.

**Comment by zhuyingSeu** [comment]
Currently, the open source model only supports the front camera.

**Comment by DecompileExpert** [comment]
can it be trained for back camera

**Comment by thuanpn19** [comment]
> Currently, the open source model only supports the front camera.

can you explain the difference between using back camera and front camera?
