### ISSUE TITLE
Structure of dataset

### ISSUE THREAD

**Issue by huylgia** [minivision-ai/Silent-Face-Anti-Spoofing#77]
Dear author,
I have some questions about the structure of the dataset. 
1)What is the sub folder "0,1,2" represent for? 
2)Num of the class is two (live and spoof), right?
3)Could you tell me that I can borrow your dataset to research?
I hope you will answer my question soon.
Best regard

**Comment by zhuyingSeu** [comment]
"0,1,2" is the example.It represents the three classes. You can define the class num according to your dataset. Our dataset is private.
