### ISSUE TITLE
训练集中 在live出现过的identity必须要在fake里也出现吗？

### ISSUE THREAD

**Issue by NingCY** [minivision-ai/Silent-Face-Anti-Spoofing#80]
请教一下，因为CelebA-Spoof这个数据集里是按照不同id给出的live/fake数据，训练活体模型的时候需不需要保持live和fake里的id一致？ 如果有些id出现在live而没有出现在fake里，那么会不会学到识别id相关的特征而不是活体的特征？ 极端的情况，训练集里只有2个数据，1个是live，1个是fake，id互斥，直觉上模型很可能学到的区分id的特征而不是活体的特征，不知道作者有没有做过类似的实验或者有一些好的经验分享吗？ 感谢！

**Comment by zhuyingSeu** [comment]
活体跟id的一致性没有关系
