### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by dara1400** [minivision-ai/Silent-Face-Anti-Spoofing#94]
Hello
I hope you are doing well.
Thanks for publishing this great job.

May I download the dataset, which you used to train the model?

**Comment by amilkcar** [comment]
Di you had luck with the dataset..... i Have a lot of images but i didnt understand how to resize/crop the images to create the dataset

**Comment by Madina-S** [comment]
@amilkcar did you solve the issue?
