### ISSUE TITLE
problem in img.unsqueeze(0).to(self.device)

### ISSUE THREAD

**Issue by AlienX456** [minivision-ai/Silent-Face-Anti-Spoofing#95]
Hi,

I have a problem when trying to run test script, when it is trying to run this line `img = img.unsqueeze(0).to(self.device)` execution gets blocked. ¿Do you know what could be happening?

Thanks!!!

**Comment by AlienX456** [comment]
I get cuDNN error: CUDNN_STATUS_MAPPING_ERROR after a while, it 's related with cuda, what version should i use?

**Comment by Nurmukhammeds** [comment]
it depends on your tensorflow version in local env that must satisfy to cuda, cudnn
